; PlatformIO Project Configuration File
;
;   UART21 Demo for XIAO nRF54LM20A
;   TX: P1.8, RX: P1.9
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:seeed-xiao-nrf54lm20a]
platform = https://github.com/Seeed-Studio/platform-seeedboards.git
framework = zephyr
board = seeed-xiao-nrf54lm20a
monitor_speed = 1000000

; upload_protocol = jlink
